### PR TITLE
Coralnewbranch

### PR DESCRIPTION
**Pull request by cmini004**
// make sure the title of your pull request is [ticket number] name 
// if changes were requested change the title to [ticket number] name WIP⚠️

**Description**

// what does your project do? 
attach any relevant screenshots

**Type of change**

- [ ] Bug Fixes
- [ ] Breaking Change
- [**] New Feature

**Have you done the following?**

- [ ] Pull from staging/master
- [ ] document your changes above
- [ ] assigned a code reviewer
- [ ] Deleted the comments in this template

### CODE REVIEW

**Comment by cmini004** [comment]
styled map component

**Comment by cmini004** [comment]
Also styled Verify/ redirect page

**Comment by leonkoech** [comment]
@cmini004 you have so many conflicts with the main branch

**Comment by cmini004** [comment]
💀

**Pull request closed without merging**
